version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: perros_app
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./init/mysql/:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-puser"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: petracker_app
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app
    command: >
      sh -c "git clone https://github.com/JoseFelixBarbRoj/isi-PeTracker.git . &&
      pip install . &&
      python project_setup.py &&
      python backend/app.py
      "
    ports:
      - "8000:8000"

volumes:
  mysql_data: