version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: perros_app
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE_TEST: perros_test
    ports:
      - "3306:3306"
    volumes:
      - ./init/mysql/:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: petracker_app
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app
    command: >
      sh -c "pip install . &&
      python project_setup.py &&
      python backend/inference/data/populate_data.py &&
      python -m unittest discover -s testing &&
      python backend/app.py
      "
    ports:
      - "5000:5000"
    volumes:
      - ./app_logs:/app/logs   

volumes:
  mysql_data: